version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.8.2
        environment:
          MIX_ENV: test

    working_directory: ~/app

    steps:
      - checkout

      - run: mix local.hex --force
      - run: mix local.rebar --force

      # cache is not used since yamler is recompiled every time
      - restore_cache: &restore_mix_cache
          keys:
            - v2-mix-cache-{{ checksum "mix.lock" }}
            - v2-mix-cache-{{ .Branch }}
            - v2-mix-cache
      - restore_cache: &restore_build_cache
          keys:
            - v2-build-cache-{{ .Branch }}
            - v2-build-cache

      - run: mix do deps.install, compile

      - save_cache:
          key: v2-mix-cache-{{ checksum "mix.lock" }}
          paths: deps
      - save_cache:
          key: v2-mix-cache-{{ .Branch }}
          paths: deps
      - save_cache:
          key: v2-mix-cache
          paths: deps
      - save_cache:
          key: v2-build-cache-{{ .Branch }}
          paths: _build
      - save_cache:
          key: v2-build-cache
          paths: _build

      - run: mix test

  deploy:
    working_directory: ~/app

    docker:
      - image: circleci/elixir:1.8.2

    steps:
      - checkout

      - run: mix local.hex --force
      - run: mix local.rebar --force

      # https://circleci.com/gh/shikimori/neko-achievements/edit#ssh
      - add_ssh_keys:
          fingerprints:
            - '21:cd:07:a3:b8:b9:1f:20:b0:eb:59:c7:e3:14:fc:5e'

      - restore_cache:
          <<: *restore_mix_cache
      - restore_cache:
          <<: *restore_build_cache

      - run: mix do deps.install, compile
      - run: mix deploy

# https://circleci.com/docs/2.0/deployment-integrations/#ssh
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
